### ISSUE TITLE
noicessss, everyone gets a pass :D 

### ISSUE THREAD

**Issue by okarem** [WebAhead5/PetSitter#15]
https://github.com/WebAhead5/PetSitter/blob/8dfc771bdc27f4138ecfe8e297c13f3fe6e48afc/src/queries/reserveCRUD.js#L88-L95

**Comment by MorisR** [comment]
the validation was done here
https://github.com/WebAhead5/PetSitter/blob/8dfc771bdc27f4138ecfe8e297c13f3fe6e48afc/src/queries/reserveCRUD.js#L41-L58

this is basically redundant code
