### ISSUE TITLE
what is this url ?

### ISSUE THREAD

**Issue by Karyum** [WebAhead5/PetSitter#18]
https://github.com/WebAhead5/PetSitter/blob/master/src/router.js#L9, the second argument is `http://localhost:3000` why is it there? and does it affect heroku ?

**Comment by MorisR** [comment]
it's just a place holder... in order to use the url.URL class ([this](https://nodejs.org/dist/latest-v14.x/docs/api/url.html#url_class_url) ) you need to pass it a http url.

it was used only to retrieve the pathname from the url without the params
