### ISSUE TITLE
What in the world is mo.min.js doing?

### ISSUE THREAD

**Issue by jrd656** [WebAhead5/PetSitter#19]
As above

**Comment by VoJunSoft** [comment]
this is a javascript animation file (library) you can use to build an animation in javascript. you can have the following link in your HTML file instead:
<script src="https://cdnjs.cloudflare.com/ajax/libs/mo-js/0.288.2/mo.min.js"></script>
however, I decided to download the file and have it on our local directory instead.

**Comment by jrd656** [comment]
Interesting. Maybe talk us through it in your presentation?
